### ISSUE TITLE
Error injecting constructor

### ISSUE THREAD

**Issue by morissette** [awslabs/logstash-input-dynamodb#20]
When running with the following conf:

```
input { 
    dynamodb{
      endpoint => "dynamodb.us-east-1.amazonaws.com" 
      streams_endpoint => "streams.dynamodb.us-east-1.amazonaws.com" 
      view_type => "new_and_old_images" 
      aws_access_key_id => "" 
      aws_secret_access_key => "" 
      table_name => "mdh_perf_data_dev"
  }
} 
output { 
    elasticsearch {
      host => "https://censor.us-east-1.es.amazonaws.com/"
    } 
    stdout { } 
}
```

I get the following errors:

```
881) Error injecting constructor, java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
  at org.elasticsearch.node.service.NodeService.<init>(Unknown Source)
  while locating org.elasticsearch.node.service.NodeService
    for parameter 5 at org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction.<init>(Unknown Source)
  while locating org.elasticsearch.action.admin.cluster.node.stats.TransportNodesStatsAction
    for parameter 2 at org.elasticsearch.cluster.InternalClusterInfoService.<init>(Unknown Source)
  while locating org.elasticsearch.cluster.InternalClusterInfoService
  while locating org.elasticsearch.cluster.ClusterInfoService
    for parameter 3 at org.elasticsearch.cluster.routing.allocation.AllocationService.<init>(Unknown Source)
  while locating org.elasticsearch.cluster.routing.allocation.AllocationService
    for parameter 5 at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.<init>(Unknown Source)
  while locating org.elasticsearch.cluster.metadata.MetaDataCreateIndexService
    for parameter 5 at org.elasticsearch.snapshots.RestoreService.<init>(Unknown Source)
  while locating org.elasticsearch.snapshots.RestoreService
Caused by: java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.

```

**Comment by morissette** [comment]
Upgrading to latest version of logstash => resolved
