### ISSUE TITLE
object mapping for [awsRegion] tried to parse field [awsRegion] as object, but found a concrete value"

### ISSUE THREAD

**Issue by asimashfaq** [awslabs/logstash-input-dynamodb#23]
Getting this error if i update the data on Dynamodb.

**Comment by asimashfaq** [comment]
elasticsearch_1  | MapperParsingException[object mapping for [awsRegion] tried to parse field [awsRegion] as object, but found a concrete value]
elasticsearch_1  |  at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:215)
elasticsearch_1  |  at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:308)
elasticsearch_1  |  at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:438)
elasticsearch_1  |  at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:264)
elasticsearch_1  |  at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:124)
elasticsearch_1  |  at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
elasticsearch_1  |  at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:529)
elasticsearch_1  |  at org.elasticsearch.index.shard.IndexShard.prepareCreateOnPrimary(IndexShard.java:506)
elasticsearch_1  |  at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(Transport

**Comment by nandini-nyllabs** [comment]
Facing the same issue

 "reason"=>"object mapping for [awsRegion] tried to parse field [awsRegion] as object, but found a concrete value"
