### ISSUE TITLE
Shard exception

### ISSUE THREAD

**Issue by fozzylyon** [awslabs/logstash-input-dynamodb#4]
I'm using this plugin as part of the follow data flow:  DynamoDB => Logstash => Elasticsearch
The plugin seems to be unable to find a shard or create a lease again after the error below.  And it seems to happen in a few scenarios:
- disabling a dynamo stream & creating a new stream
- deleting items from dynamo

I wish I had some hard steps to reproduce the issue, but a single pattern hasn't shown itself yet.
But I've tried a few things:
- Isolating the logstash instance on it's own ec2 instance
- Using a generic file output instead of the elasticsearch output
- Wiping the elasticsearch index before starting logstash
- Disabling perform_scan

I can paste more logs or link to a pastebin, but the non debug error and warning I see are:

```
ERROR: com.amazonaws.services.dynamodbv2.streamsadapter.model.AmazonServiceExceptionTransformer: DynamoDB Streams exception: class com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException tranformed to Kinesis class com.amazonaws.services.kinesis.model.ResourceNotFoundException
com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found: Shard does not exist (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: JQHMLS2F58S2N7U2H47AMQDDB7VV4KQNSO5AEMVJF66Q9ASUAAJG)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.invoke(AmazonDynamoDBStreamsClient.java:634)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.getShardIterator(AmazonDynamoDBStreamsClient.java:518)
    at com.amazonaws.services.dynamodbv2.streamsadapter.AmazonDynamoDBStreamsAdapterClient.getShardIterator(AmazonDynamoDBStreamsAdapterClient.java:378)
    at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getIterator(KinesisProxy.java:271)
    at com.amazonaws.services.kinesis.clientlibrary.proxies.MetricsCollectingKinesisProxyDecorator.getIterator(MetricsCollectingKinesisProxyDecorator.java:123)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.getIterator(KinesisDataFetcher.java:135)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.advanceIteratorTo(KinesisDataFetcher.java:111)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.initialize(KinesisDataFetcher.java:90)
input {
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:77)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
    at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
WARN: com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy: Cannot find the shard given the shardId shardId-xxxxxxxxxxxxxxxxxxxx-yyyyyyyy
```

_UPDATE_
Including the logstash config

``` ruby
input {
    dynamodb {
        endpoint => "dynamodb.us-west-2.amazonaws.com"
        streams_endpoint => "streams.dynamodb.us-west-2.amazonaws.com"
        view_type => "new_image"
        aws_access_key_id => "xxxxxxxxxxxxxxxxxxxx"
        aws_secret_access_key => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        table_name => "output-data"
        type => "output-data"
        log_format => "json_drop_binary"
    }
}

filter {
    if [type] == "output-data" {
        json {
            source => "message"
            add_field => {
                 "output_id" => "%{_id}"
            }
            remove_field => ["message", "host", "@version"]
        }
    }
}

output {
    if [type] == "output-data" {
        file {
            path => "./test-%{+YYYY-MM-dd}.txt"
        }
        elasticsearch {
            host => ["x.x.x.x:9200"]
            cluster => "elasticsearch_stage"
            index => "output-data"
            document_type => "output"
            protocol => "http"
            document_id => "%{_id}"
        }
    }
}
```

**Comment by agaur-aws** [comment]
I presume this is happening because when you delete a stream and recreate it, the stream ARN changes, which is why you see the Resource Not Found Exception since the worker is throwing this exception. 
 This use case is currently unsupported : was there a specific reason for the need to disable a stream currently being processed and recreating a new stream?

**Comment by fozzylyon** [comment]
@agaur-aws I'll only delete and create streams while logstash (and the plugin) isn't running.  But it still seems to contribute to these errors after logstash is restarted.

I'll keep trying to debug the issue and find clean steps to repro.

**Comment by fozzylyon** [comment]
Another instance of the error occurred while it was performing an initial scan:

```
WARN: com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy: Cannot find the shard given the shardId shardId-00000001446500994480-a69421f6
ERROR: com.amazonaws.services.dynamodbv2.streamsadapter.model.AmazonServiceExceptionTransformer: DynamoDB Streams exception: class com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException tranformed to Kinesis class com.amazonaws.services.kinesis.model.ResourceNotFoundException
com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found: Shard does not exist (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 7ER46GTKRBKV0V82GNTJDO1SDJVV4KQNSO5AEMVJF66Q9ASUAAJG)
  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.invoke(AmazonDynamoDBStreamsClient.java:634)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.getShardIterator(AmazonDynamoDBStreamsClient.java:518)
  at com.amazonaws.services.dynamodbv2.streamsadapter.AmazonDynamoDBStreamsAdapterClient.getShardIterator(AmazonDynamoDBStreamsAdapterClient.java:378)
  at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getIterator(KinesisProxy.java:271)
  at com.amazonaws.services.kinesis.clientlibrary.proxies.MetricsCollectingKinesisProxyDecorator.getIterator(MetricsCollectingKinesisProxyDecorator.java:123)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.getIterator(KinesisDataFetcher.java:135)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.advanceIteratorTo(KinesisDataFetcher.java:111)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.initialize(KinesisDataFetcher.java:90)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:77)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
WARN: com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy: Cannot find the shard given the shardId shardId-00000001446516990572-4e28847d
ERROR: com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask: Application exception.
com.amazonaws.services.kinesis.clientlibrary.exceptions.ShutdownException: Can't update checkpoint - instance doesn't hold the lease for this shard
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisClientLibLeaseCoordinator.setCheckpoint(com/amazonaws/services/kinesis/clientlibrary/lib/worker/KinesisClientLibLeaseCoordinator.java:120)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.advancePosition(com/amazonaws/services/kinesis/clientlibrary/lib/worker/RecordProcessorCheckpointer.java:216)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.RecordProcessorCheckpointer.checkpoint(com/amazonaws/services/kinesis/clientlibrary/lib/worker/RecordProcessorCheckpointer.java:77)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:483)
  at RUBY.shutdown(/opt/logstash/vendor/local_gems/b42e9da0/logstash-input-dynamodb-1.0.0-java/lib/logstash/inputs/LogStashRecordProcessor.rb:56)
  at Logstash$$Inputs$$DynamoDB$$LogStashRecordProcessor_580099813.shutdown(Logstash$$Inputs$$DynamoDB$$LogStashRecordProcessor_580099813.gen:13)
  at Logstash$$Inputs$$DynamoDB$$LogStashRecordProcessor_580099813.shutdown(Logstash$$Inputs$$DynamoDB$$LogStashRecordProcessor_580099813.gen:13)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.V1ToV2RecordProcessorAdapter.shutdown(com/amazonaws/services/kinesis/clientlibrary/lib/worker/V1ToV2RecordProcessorAdapter.java:48)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShutdownTask.call(com/amazonaws/services/kinesis/clientlibrary/lib/worker/ShutdownTask.java:100)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(com/amazonaws/services/kinesis/clientlibrary/lib/worker/MetricsCollectingTaskDecorator.java:49)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(com/amazonaws/services/kinesis/clientlibrary/lib/worker/MetricsCollectingTaskDecorator.java:24)
  at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(java/lang/Thread.java:745)
ERROR: com.amazonaws.services.dynamodbv2.streamsadapter.model.AmazonServiceExceptionTransformer: DynamoDB Streams exception: class com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException tranformed to Kinesis class com.amazonaws.services.kinesis.model.ResourceNotFoundException
com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found: Shard does not exist (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: GLAR315VLS5COGAIATENM0NLDFVV4KQNSO5AEMVJF6RQ8ASUAAJG)
  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.invoke(AmazonDynamoDBStreamsClient.java:634)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.getShardIterator(AmazonDynamoDBStreamsClient.java:518)
  at com.amazonaws.services.dynamodbv2.streamsadapter.AmazonDynamoDBStreamsAdapterClient.getShardIterator(AmazonDynamoDBStreamsAdapterClient.java:378)
  at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getIterator(KinesisProxy.java:271)
  at com.amazonaws.services.kinesis.clientlibrary.proxies.MetricsCollectingKinesisProxyDecorator.getIterator(MetricsCollectingKinesisProxyDecorator.java:123)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.getIterator(KinesisDataFetcher.java:135)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.advanceIteratorTo(KinesisDataFetcher.java:111)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.KinesisDataFetcher.initialize(KinesisDataFetcher.java:90)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.InitializeTask.call(InitializeTask.java:77)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
  at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:24)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
WARN: com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy: Cannot find the shard given the shardId shardId-00000001446486892701-b695771f
```

**Comment by raymolin** [comment]
The logstash plugin under the hood uses the KCL library to streams processing, and as a byproduct create a DynamoDB table to store meaningful state/checkpoints.  I won't go into too details here, but basically that state involves saving shard-id's and their last evaluated record.  What's happening is now, this checkpointer is being used when you recreated the stream and the shard has expired.  

The fix is a simple one simply drop the table called "logstash_input_dynamodb_cptr" in the DynamoDB console, and restart your logstash plugin.  If you want to define the name of this DynamoDB table in the future check out this config value.
:checkpointer, :validate => :string, :default => "logstash_input_dynamodb_cptr"

**Comment by fozzylyon** [comment]
@raymolin That was really helpful to resolve the consistent shard errors, thanks!  I have a process in place to avoid the problem again, so closing for now.

Thanks again

**Comment by jeevanvijay** [comment]
Hi Fozzylon,

I am facing the same problem now. deleting "logstash_input_dynamodb_cptr" is not helping.  Would you please provide more details on how you were able to avoid the problem. 

Appreciate your help.

Thanks,
Jeevan.

**Comment by brett--anderson** [comment]
@jeevanvijay This might be a little late, but for anyone else still getting this error, sometimes disabling the streams on the tables you are trying to track, then re-enabling them, solves this problem. Disable Logstash, reset the streams in this fashion, delete the checkpoint table "logstash_input_dynamodb_cptr", then restart Logstash. Presumably the stale streams reference data that no longer exists in the table. Dropping and recreating the tables will of course achieve the same result, if you're able to do that.

**Comment by avtaniket** [comment]
@raymolin , I suggested by @jeevanvijay I tried deleting table & restart logstash... but still after some time, error generates again

And unfortunately i have restart logstash to make it working again.

Can you please share solution (alternate automate process) to handle this issue.
